# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: AppSick Frontend CI

on:
  push:
    branches: ["development"]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: ["development"]
    paths-ignore:
      - "*.md"

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install deps
      - name: Install deps
        run: npm ci

      # Build
      - name: Build
        run: npm run build --if-present

      # Test
      - name: Test
        run: npm test
